package codegen

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/mitchellnemitz/wisp/internal/parser"
	"github.com/mitchellnemitz/wisp/internal/types"
)

// compile lexes, parses, checks, and generates src, failing the test on any
// compile error.
func compile(t *testing.T, src string) []byte {
	t.Helper()
	prog, err := parser.Parse(src, "test.wisp")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	info := types.Check(prog)
	if len(info.Errors) > 0 {
		t.Fatalf("check errors: %v", info.Errors)
	}
	out, err := Generate(prog, info)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return out
}

// run writes script to a temp file and runs it under dash, returning
// stdout/stderr/exit. Skips if dash is unavailable.
func run(t *testing.T, script []byte) (string, string, int) {
	t.Helper()
	dash, err := exec.LookPath("dash")
	if err != nil {
		t.Skip("dash not available")
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "out.sh")
	if err := os.WriteFile(path, script, 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(dash, path)
	var out, errb strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errb
	err = cmd.Run()
	code := 0
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			code = ee.ExitCode()
		} else {
			t.Fatalf("run: %v", err)
		}
	}
	return out.String(), errb.String(), code
}

// shellcheck runs shellcheck on the script; it fails the test on a finding and
// skips if shellcheck is unavailable.
func shellcheck(t *testing.T, script []byte) {
	t.Helper()
	sc, err := exec.LookPath("shellcheck")
	if err != nil {
		t.Skip("shellcheck not available")
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "out.sh")
	if err := os.WriteFile(path, script, 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(sc, "--shell", "sh", "--severity", "warning", path)
	var out strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		t.Fatalf("shellcheck found issues:\n%s\n--- script ---\n%s", out.String(), script)
	}
}

// runWisp is the common path: compile, shellcheck, run.
func runWisp(t *testing.T, src string) (string, string, int) {
	t.Helper()
	script := compile(t, src)
	shellcheck(t, script)
	return run(t, script)
}

func TestHelloWorld(t *testing.T) {
	out, errb, code := runWisp(t, `fn main() -> int {
  print("hello, world")
  return 0
}`)
	if code != 0 {
		t.Fatalf("exit = %d stderr=%q", code, errb)
	}
	if out != "hello, world\n" {
		t.Fatalf("stdout = %q", out)
	}
}

func TestOutputShape(t *testing.T) {
	script := compile(t, `fn main() -> int {
  print("hi")
  return 0
}`)
	s := string(script)
	if !strings.HasPrefix(s, "#!/bin/sh\n") {
		t.Fatalf("missing shebang:\n%s", s)
	}
	if !strings.Contains(s, "# generated by wisp; do not edit") {
		t.Fatalf("missing banner")
	}
	if !strings.Contains(s, "__wisp_f_m0_main; exit \"$__ret\"") {
		t.Fatalf("missing main invocation/exit:\n%s", s)
	}
	if !strings.Contains(s, "# test.wisp:1") {
		t.Fatalf("missing per-function source comment:\n%s", s)
	}
}

// TestHeaderHasZshWordSplitShim asserts the generated header carries the zsh
// word-splitting shim, in the current shell (not a subshell) and guarded by
// ZSH_VERSION so it is a no-op under dash/busybox/bash. The shim also raises the
// zsh FUNCNEST ceiling so deep recursion matches the other shells (M5).
func TestHeaderHasZshWordSplitShim(t *testing.T) {
	s := string(compile(t, "fn main() -> int {\nreturn 0\n}\n"))
	const shim = `if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi`
	if !strings.Contains(s, shim) {
		t.Fatalf("missing zsh word-split + FUNCNEST shim:\n%s", s)
	}
	if !strings.HasPrefix(s, "#!/bin/sh\n") {
		t.Fatalf("shebang must stay #!/bin/sh:\n%s", s)
	}
}

// TestFloatContainsUsesFcmp asserts float membership compares by NUMERIC
// identity via __wisp_fcmp (SC-025), never a byte-text `[ "$a" = "$b" ]` test
// which would split 1.0/1.00. SC-025(c): the operands must reach __wisp_fcmp as
// double-quoted "$var" expansions of spilled temps, never interpolated as raw
// program text.
func TestFloatContainsUsesFcmp(t *testing.T) {
	src := `fn main() -> int { let xs: float[] = [1.0, 2.5]; print("${array.contains(xs, 1.00)}"); return 0 }`
	sh := string(compileNS(t, src, "array"))
	if !strings.Contains(sh, "__wisp_fcmp") {
		t.Errorf("float contains must compare via __wisp_fcmp; got:\n%s", sh)
	}
	quoted := false
	for _, ln := range strings.Split(sh, "\n") {
		if strings.Contains(ln, "__wisp_fcmp") && strings.Contains(ln, "\"$") {
			quoted = true
			break
		}
	}
	if !quoted {
		t.Errorf("SC-025(c): float contains operands must reach __wisp_fcmp as quoted \"$...\" expansions; got:\n%s", sh)
	}
}

// classifyBody isolates the compiled "classify" function's body: from its
// definition header to the next top-level function header (or end). Function
// defs are `__wisp_f_...() {` at column 0. Scoping to the function body avoids
// a false-fail from an unrelated prelude helper's own `esac`/`case`.
func classifyBody(t *testing.T, sh string) string {
	t.Helper()
	re := regexp.MustCompile(`(?m)^__wisp_f_[A-Za-z0-9_]*classify[A-Za-z0-9_]*\(\) \{`)
	loc := re.FindStringIndex(sh)
	if loc == nil {
		t.Fatalf("could not locate the classify function in:\n%s", sh)
	}
	rest := sh[loc[1]:]
	if next := regexp.MustCompile(`(?m)^__wisp_f_`).FindStringIndex(rest); next != nil {
		rest = rest[:next[0]]
	}
	return rest
}

// TestFloatSwitchUsesFcmpNotCaseGlob asserts a float switch lowers to __wisp_fcmp
// comparisons, never a `case ... esac` shell glob over the subject (SC-025(a)):
// a case-glob would put the float subject/literals through shell glob matching,
// which is wrong for numeric identity.
func TestFloatSwitchUsesFcmpNotCaseGlob(t *testing.T) {
	src := `fn classify(x: float) -> string {
  switch (x) { case 1.0 { return "one" } case 2.5 { return "two" } default { return "o" } }
}
fn main() -> int { print(classify(1.0)); return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_fcmp") {
		t.Errorf("float switch must compare via __wisp_fcmp; got:\n%s", sh)
	}
	rest := classifyBody(t, sh)
	if strings.Contains(rest, "esac") {
		t.Errorf("float switch must lower to if/elif, not a case...esac glob; classify body:\n%s", rest)
	}
	// SC-025(a) binds to the fixture's OWN case literals: the known literals 1.0
	// and 2.5 must be present in the classify body (they are the numerically
	// compared case values) and, given the no-`esac` assertion above, they
	// therefore cannot appear as a %.17g glob inside a `case "$subject" in ...
	// esac`.
	for _, lit := range []string{"1.0", "2.5"} {
		if !strings.Contains(rest, lit) {
			t.Errorf("SC-025(a): case literal %s must appear in the classify body (the compared value); body:\n%s", lit, rest)
		}
	}
}

// TestFloatSwitchSpillsSubjectOnce asserts SC-026 structurally: the compiled
// output spills the float switch subject to a SINGLE temp reused by every
// __wisp_fcmp comparison, never re-evaluated per case.
func TestFloatSwitchSpillsSubjectOnce(t *testing.T) {
	src := `fn classify(x: float) -> string {
  switch (x) { case 1.0 { return "one" } case 2.5 { return "two" } default { return "o" } }
}
fn main() -> int { print(classify(1.0)); return 0 }`
	sh := string(compile(t, src))
	body := classifyBody(t, sh)
	// Each case emits one __wisp_fcmp comparison line. The single spilled subject
	// temp is the wisp temp variable common to EVERY such line (the per-case value
	// temps differ line to line). Assert exactly one temp is shared across all
	// comparisons -> the subject was spilled once and reused, not re-evaluated.
	varRe := regexp.MustCompile(`\$\{?(__wisp_[A-Za-z0-9_]+)`)
	var fcmpLines []string
	for _, ln := range strings.Split(body, "\n") {
		if strings.Contains(ln, "__wisp_fcmp") {
			fcmpLines = append(fcmpLines, ln)
		}
	}
	if len(fcmpLines) < 2 {
		t.Fatalf("expected >=2 __wisp_fcmp case comparisons (one per non-default case), got %d in:\n%s", len(fcmpLines), body)
	}
	shared := map[string]int{}
	for _, ln := range fcmpLines {
		seen := map[string]bool{}
		for _, m := range varRe.FindAllStringSubmatch(ln, -1) {
			if !seen[m[1]] {
				seen[m[1]] = true
				shared[m[1]]++
			}
		}
	}
	var subjectTemps []string
	for v, n := range shared {
		if n == len(fcmpLines) {
			subjectTemps = append(subjectTemps, v)
		}
	}
	if len(subjectTemps) != 1 {
		t.Fatalf("SC-026: expected exactly one subject temp reused across all %d fcmp comparisons, got %v in:\n%s", len(fcmpLines), subjectTemps, body)
	}
	// SC-025(c): the spilled subject operand reaches __wisp_fcmp as a quoted
	// "$..." expansion (runtime data). The case-value operand is a raw
	// compiler-emitted float literal (the one permitted unquoted case) so it is
	// not asserted quoted here.
	for _, ln := range fcmpLines {
		if !strings.Contains(ln, "\"$") {
			t.Errorf("SC-025(c): the spilled float switch subject must reach __wisp_fcmp as a quoted \"$...\" expansion; line: %s", ln)
		}
	}
}
