package codegen

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mitchellnemitz/wisp/internal/parser"
	"github.com/mitchellnemitz/wisp/internal/types"
)

// compile lexes, parses, checks, and generates src, failing the test on any
// compile error.
func compile(t *testing.T, src string) []byte {
	t.Helper()
	prog, err := parser.Parse(src, "test.wisp")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	info := types.Check(prog)
	if len(info.Errors) > 0 {
		t.Fatalf("check errors: %v", info.Errors)
	}
	out, err := Generate(prog, info)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return out
}

// run writes script to a temp file and runs it under dash, returning
// stdout/stderr/exit. Skips if dash is unavailable.
func run(t *testing.T, script []byte) (string, string, int) {
	t.Helper()
	dash, err := exec.LookPath("dash")
	if err != nil {
		t.Skip("dash not available")
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "out.sh")
	if err := os.WriteFile(path, script, 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(dash, path)
	var out, errb strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errb
	err = cmd.Run()
	code := 0
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			code = ee.ExitCode()
		} else {
			t.Fatalf("run: %v", err)
		}
	}
	return out.String(), errb.String(), code
}

// shellcheck runs shellcheck on the script; it fails the test on a finding and
// skips if shellcheck is unavailable.
func shellcheck(t *testing.T, script []byte) {
	t.Helper()
	sc, err := exec.LookPath("shellcheck")
	if err != nil {
		t.Skip("shellcheck not available")
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "out.sh")
	if err := os.WriteFile(path, script, 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(sc, "--shell", "sh", "--severity", "warning", path)
	var out strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		t.Fatalf("shellcheck found issues:\n%s\n--- script ---\n%s", out.String(), script)
	}
}

// runWisp is the common path: compile, shellcheck, run.
func runWisp(t *testing.T, src string) (string, string, int) {
	t.Helper()
	script := compile(t, src)
	shellcheck(t, script)
	return run(t, script)
}

func TestHelloWorld(t *testing.T) {
	out, errb, code := runWisp(t, `fn main() -> int {
  print("hello, world")
  return 0
}`)
	if code != 0 {
		t.Fatalf("exit = %d stderr=%q", code, errb)
	}
	if out != "hello, world\n" {
		t.Fatalf("stdout = %q", out)
	}
}

func TestOutputShape(t *testing.T) {
	script := compile(t, `fn main() -> int {
  print("hi")
  return 0
}`)
	s := string(script)
	if !strings.HasPrefix(s, "#!/bin/sh\n") {
		t.Fatalf("missing shebang:\n%s", s)
	}
	if !strings.Contains(s, "# generated by wisp; do not edit") {
		t.Fatalf("missing banner")
	}
	if !strings.Contains(s, "__wisp_f_m0_main; exit \"$__ret\"") {
		t.Fatalf("missing main invocation/exit:\n%s", s)
	}
	if !strings.Contains(s, "# test.wisp:1") {
		t.Fatalf("missing per-function source comment:\n%s", s)
	}
}

// TestHeaderHasZshWordSplitShim asserts the generated header carries the zsh
// word-splitting shim, in the current shell (not a subshell) and guarded by
// ZSH_VERSION so it is a no-op under dash/busybox/bash. The shim also raises the
// zsh FUNCNEST ceiling so deep recursion matches the other shells (M5).
func TestHeaderHasZshWordSplitShim(t *testing.T) {
	s := string(compile(t, "fn main() -> int {\nreturn 0\n}\n"))
	const shim = `if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi`
	if !strings.Contains(s, shim) {
		t.Fatalf("missing zsh word-split + FUNCNEST shim:\n%s", s)
	}
	if !strings.HasPrefix(s, "#!/bin/sh\n") {
		t.Fatalf("shebang must stay #!/bin/sh:\n%s", s)
	}
}

// TestFloatContainsUsesFcmp asserts float membership compares by NUMERIC
// identity via __wisp_fcmp (SC-025), never a byte-text `[ "$a" = "$b" ]` test
// which would split 1.0/1.00. SC-025(c): the operands must reach __wisp_fcmp as
// double-quoted "$var" expansions of spilled temps, never interpolated as raw
// program text.
func TestFloatContainsUsesFcmp(t *testing.T) {
	src := `fn main() -> int { let xs: float[] = [1.0, 2.5]; print("${array.contains(xs, 1.00)}"); return 0 }`
	sh := string(compileNS(t, src, "array"))
	if !strings.Contains(sh, "__wisp_fcmp") {
		t.Errorf("float contains must compare via __wisp_fcmp; got:\n%s", sh)
	}
	quoted := false
	for _, ln := range strings.Split(sh, "\n") {
		if strings.Contains(ln, "__wisp_fcmp") && strings.Contains(ln, "\"$") {
			quoted = true
			break
		}
	}
	if !quoted {
		t.Errorf("SC-025(c): float contains operands must reach __wisp_fcmp as quoted \"$...\" expansions; got:\n%s", sh)
	}
}
