package codegen

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/mitchellnemitz/wisp/internal/parser"
	"github.com/mitchellnemitz/wisp/internal/types"
)

// compile lexes, parses, checks, and generates src, failing the test on any
// compile error.
func compile(t *testing.T, src string) []byte {
	t.Helper()
	prog, err := parser.Parse(src, "test.wisp")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	info := types.Check(prog)
	if len(info.Errors) > 0 {
		t.Fatalf("check errors: %v", info.Errors)
	}
	out, err := Generate(prog, info)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return out
}

// run writes script to a temp file and runs it under dash, returning
// stdout/stderr/exit. Skips if dash is unavailable.
func run(t *testing.T, script []byte) (string, string, int) {
	t.Helper()
	dash, err := exec.LookPath("dash")
	if err != nil {
		t.Skip("dash not available")
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "out.sh")
	if err := os.WriteFile(path, script, 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(dash, path)
	var out, errb strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errb
	err = cmd.Run()
	code := 0
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			code = ee.ExitCode()
		} else {
			t.Fatalf("run: %v", err)
		}
	}
	return out.String(), errb.String(), code
}

// shellcheck runs shellcheck on the script; it fails the test on a finding and
// skips if shellcheck is unavailable.
func shellcheck(t *testing.T, script []byte) {
	t.Helper()
	sc, err := exec.LookPath("shellcheck")
	if err != nil {
		t.Skip("shellcheck not available")
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "out.sh")
	if err := os.WriteFile(path, script, 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(sc, "--shell", "sh", "--severity", "warning", path)
	var out strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		t.Fatalf("shellcheck found issues:\n%s\n--- script ---\n%s", out.String(), script)
	}
}

// runWisp is the common path: compile, shellcheck, run.
func runWisp(t *testing.T, src string) (string, string, int) {
	t.Helper()
	script := compile(t, src)
	shellcheck(t, script)
	return run(t, script)
}

func TestHelloWorld(t *testing.T) {
	out, errb, code := runWisp(t, `fn main() -> int {
  print("hello, world")
  return 0
}`)
	if code != 0 {
		t.Fatalf("exit = %d stderr=%q", code, errb)
	}
	if out != "hello, world\n" {
		t.Fatalf("stdout = %q", out)
	}
}

func TestOutputShape(t *testing.T) {
	script := compile(t, `fn main() -> int {
  print("hi")
  return 0
}`)
	s := string(script)
	if !strings.HasPrefix(s, "#!/bin/sh\n") {
		t.Fatalf("missing shebang:\n%s", s)
	}
	if !strings.Contains(s, "# generated by wisp; do not edit") {
		t.Fatalf("missing banner")
	}
	if !strings.Contains(s, "__wisp_f_m0_main; exit \"$__ret\"") {
		t.Fatalf("missing main invocation/exit:\n%s", s)
	}
	if !strings.Contains(s, "# test.wisp:1") {
		t.Fatalf("missing per-function source comment:\n%s", s)
	}
}

// TestHeaderHasZshWordSplitShim asserts the generated header carries the zsh
// word-splitting shim, in the current shell (not a subshell) and guarded by
// ZSH_VERSION so it is a no-op under dash/busybox/bash. The shim also raises the
// zsh FUNCNEST ceiling so deep recursion matches the other shells (M5).
func TestHeaderHasZshWordSplitShim(t *testing.T) {
	s := string(compile(t, "fn main() -> int {\nreturn 0\n}\n"))
	const shim = `if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi`
	if !strings.Contains(s, shim) {
		t.Fatalf("missing zsh word-split + FUNCNEST shim:\n%s", s)
	}
	if !strings.HasPrefix(s, "#!/bin/sh\n") {
		t.Fatalf("shebang must stay #!/bin/sh:\n%s", s)
	}
}

// TestFloatContainsUsesFcmp asserts float membership compares by NUMERIC
// identity via __wisp_fcmp (SC-025), never a byte-text `[ "$a" = "$b" ]` test
// which would split 1.0/1.00. SC-025(c): the operands must reach __wisp_fcmp as
// double-quoted "$var" expansions of spilled temps, never interpolated as raw
// program text.
func TestFloatContainsUsesFcmp(t *testing.T) {
	src := `fn main() -> int { let xs: float[] = [1.0, 2.5]; print("${array.contains(xs, 1.00)}"); return 0 }`
	sh := string(compileNS(t, src, "array"))
	if !strings.Contains(sh, "__wisp_fcmp") {
		t.Errorf("float contains must compare via __wisp_fcmp; got:\n%s", sh)
	}
	quoted := false
	for _, ln := range strings.Split(sh, "\n") {
		if strings.Contains(ln, "__wisp_fcmp") && strings.Contains(ln, "\"$") {
			quoted = true
			break
		}
	}
	if !quoted {
		t.Errorf("SC-025(c): float contains operands must reach __wisp_fcmp as quoted \"$...\" expansions; got:\n%s", sh)
	}
}

// TestFloatBackedEnumMembershipUsesFcmp asserts a float-backed value enum's
// membership compare routes through comparesAsFloat's enum arm (Task 2) and
// __wisp_fcmp, not a byte-text `=` test (SC-024).
func TestFloatBackedEnumMembershipUsesFcmp(t *testing.T) {
	src := `enum Ratio: float { Half = 0.5, Full = 1.0 }
fn main() -> int { let xs: Ratio[] = [Ratio.Half]; print("${array.contains(xs, Ratio.Half)}"); return 0 }`
	sh := string(compileNS(t, src, "array"))
	if !strings.Contains(sh, "__wisp_fcmp") {
		t.Errorf("float-backed-enum membership must compare via __wisp_fcmp (comparesAsFloat enum arm); got:\n%s", sh)
	}
}

// classifyBody isolates the compiled "classify" function's body: from its
// definition header to the next top-level function header (or end). Function
// defs are `__wisp_f_...() {` at column 0. Scoping to the function body avoids
// a false-fail from an unrelated prelude helper's own `esac`/`case`.
func classifyBody(t *testing.T, sh string) string {
	t.Helper()
	re := regexp.MustCompile(`(?m)^__wisp_f_[A-Za-z0-9_]*classify[A-Za-z0-9_]*\(\) \{`)
	loc := re.FindStringIndex(sh)
	if loc == nil {
		t.Fatalf("could not locate the classify function in:\n%s", sh)
	}
	rest := sh[loc[1]:]
	if next := regexp.MustCompile(`(?m)^__wisp_f_`).FindStringIndex(rest); next != nil {
		rest = rest[:next[0]]
	}
	return rest
}

// TestFloatSwitchUsesFcmpNotCaseGlob asserts a float switch lowers to __wisp_fcmp
// comparisons, never a `case ... esac` shell glob over the subject (SC-025(a)):
// a case-glob would put the float subject/literals through shell glob matching,
// which is wrong for numeric identity.
func TestFloatSwitchUsesFcmpNotCaseGlob(t *testing.T) {
	src := `fn classify(x: float) -> string {
  switch (x) { case 1.0 { return "one" } case 2.5 { return "two" } default { return "o" } }
}
fn main() -> int { print(classify(1.0)); return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_fcmp") {
		t.Errorf("float switch must compare via __wisp_fcmp; got:\n%s", sh)
	}
	rest := classifyBody(t, sh)
	if strings.Contains(rest, "esac") {
		t.Errorf("float switch must lower to if/elif, not a case...esac glob; classify body:\n%s", rest)
	}
	// SC-025(a) binds to the fixture's OWN case literals: the known literals 1.0
	// and 2.5 must be present in the classify body (they are the numerically
	// compared case values) and, given the no-`esac` assertion above, they
	// therefore cannot appear as a %.17g glob inside a `case "$subject" in ...
	// esac`.
	for _, lit := range []string{"1.0", "2.5"} {
		if !strings.Contains(rest, lit) {
			t.Errorf("SC-025(a): case literal %s must appear in the classify body (the compared value); body:\n%s", lit, rest)
		}
	}
}

// TestFloatSwitchSpillsSubjectOnce asserts SC-026 structurally: the compiled
// output spills the float switch subject to a SINGLE temp reused by every
// __wisp_fcmp comparison, never re-evaluated per case.
func TestFloatSwitchSpillsSubjectOnce(t *testing.T) {
	src := `fn classify(x: float) -> string {
  switch (x) { case 1.0 { return "one" } case 2.5 { return "two" } default { return "o" } }
}
fn main() -> int { print(classify(1.0)); return 0 }`
	sh := string(compile(t, src))
	body := classifyBody(t, sh)
	// Each case emits one __wisp_fcmp comparison line. The single spilled subject
	// temp is the wisp temp variable common to EVERY such line (the per-case value
	// temps differ line to line). Assert exactly one temp is shared across all
	// comparisons -> the subject was spilled once and reused, not re-evaluated.
	varRe := regexp.MustCompile(`\$\{?(__wisp_[A-Za-z0-9_]+)`)
	var fcmpLines []string
	for _, ln := range strings.Split(body, "\n") {
		if strings.Contains(ln, "__wisp_fcmp") {
			fcmpLines = append(fcmpLines, ln)
		}
	}
	if len(fcmpLines) < 2 {
		t.Fatalf("expected >=2 __wisp_fcmp case comparisons (one per non-default case), got %d in:\n%s", len(fcmpLines), body)
	}
	shared := map[string]int{}
	for _, ln := range fcmpLines {
		seen := map[string]bool{}
		for _, m := range varRe.FindAllStringSubmatch(ln, -1) {
			if !seen[m[1]] {
				seen[m[1]] = true
				shared[m[1]]++
			}
		}
	}
	var subjectTemps []string
	for v, n := range shared {
		if n == len(fcmpLines) {
			subjectTemps = append(subjectTemps, v)
		}
	}
	if len(subjectTemps) != 1 {
		t.Fatalf("SC-026: expected exactly one subject temp reused across all %d fcmp comparisons, got %v in:\n%s", len(fcmpLines), subjectTemps, body)
	}
	// SC-025(c): the spilled subject operand reaches __wisp_fcmp as a quoted
	// "$..." expansion (runtime data). The case-value operand is a raw
	// compiler-emitted float literal (the one permitted unquoted case) so it is
	// not asserted quoted here.
	for _, ln := range fcmpLines {
		if !strings.Contains(ln, "\"$") {
			t.Errorf("SC-025(c): the spilled float switch subject must reach __wisp_fcmp as a quoted \"$...\" expansion; line: %s", ln)
		}
	}
}

func TestFloatDictKeyUsesFkey(t *testing.T) { // SC-025(b)
	src := `fn main() -> int { let m: {float: int} = {}; m[1.0] = 1; return 0 }`
	sh := string(compile(t, src))
	// The float key must canonicalize via __wisp_fkey (NOT the non-key float
	// stringifier __wisp_fstr, which does not fold the sign of zero and so would
	// split -0.0/0.0 as dict keys).
	if !strings.Contains(sh, "__wisp_fkey") {
		t.Errorf("float dict key must canonicalize via __wisp_fkey; got:\n%s", sh)
	}
	if strings.Contains(sh, "__wisp_fstr") {
		t.Errorf("float dict key must use the key canonicalizer __wisp_fkey, not __wisp_fstr; got:\n%s", sh)
	}
	// The __wisp_fkey helper body itself must carry the two invariants FR-013
	// names: the LC_ALL=C pin (cross-shell %.17g determinism) and the numeric
	// zero-fold (x==0 -> "0", folding -0.0/0.0). Assert these WITHIN the sliced
	// __wisp_fkey definition, NOT against the whole script: __wisp_dkey_enc is
	// co-emitted with any float dict key and itself contains `LC_ALL=C`
	// (prelude.go, `local LC_ALL; LC_ALL=C`), so a whole-script Contains("LC_ALL=C")
	// passes even if __wisp_fkey dropped its own pin -- a vacuous guard. Slice the
	// helper body the same way the classify-switch greps scope to their function.
	start := strings.Index(sh, "__wisp_fkey() {")
	if start < 0 {
		t.Fatalf("expected a __wisp_fkey() definition in output; got:\n%s", sh)
	}
	// The body runs to the first line-start `}` after the header (helpers are
	// emitted with the closing brace at column 0, `\n}`).
	rest := sh[start:]
	end := strings.Index(rest, "\n}")
	if end < 0 {
		t.Fatalf("could not find the end of the __wisp_fkey body; got:\n%s", rest)
	}
	fkeyBody := rest[:end]
	if !strings.Contains(fkeyBody, "LC_ALL=C") {
		t.Errorf("__wisp_fkey body must pin LC_ALL=C for cross-shell %%.17g determinism; got:\n%s", fkeyBody)
	}
	if !strings.Contains(fkeyBody, "==0") && !strings.Contains(fkeyBody, "== 0") {
		t.Errorf("__wisp_fkey body must numerically fold the sign of zero (x==0); got:\n%s", fkeyBody)
	}
}

func TestStringDictKeyOffAwkVChannel(t *testing.T) { // SC-025(c)
	src := `fn main() -> int { let m: {string: int} = {}; m["k"] = 1; return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_dkey_enc") {
		t.Errorf("string dict key must route through __wisp_dkey_enc; got:\n%s", sh)
	}
	// A string key must never reach __wisp_fkey (the only helper that feeds a key
	// value to an awk -v channel); only float keys legitimately do.
	if strings.Contains(sh, "__wisp_fkey") {
		t.Errorf("string dict key must not touch the float awk -v channel; got:\n%s", sh)
	}
}

func TestFloatEnumDictKeyUsesFkey(t *testing.T) { // SC-033 / FR-012 backing dispatch
	src := `enum Ratio: float { Half = 0.5, Full = 1.0 }
fn main() -> int { let m: {Ratio: int} = {}; m[Ratio.Half] = 1; return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_fkey") {
		t.Errorf("float-backed-enum dict key must resolve to backing float and use __wisp_fkey; got:\n%s", sh)
	}
	if strings.Contains(sh, "__wisp_int") {
		t.Errorf("float-backed-enum key must NOT take the int canonicalizer path; got:\n%s", sh)
	}
}

func TestBoolDictKeyOffAwkVChannel(t *testing.T) { // SC-025(c)
	src := `fn main() -> int { let m: {bool: int} = {}; m[true] = 1; return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_dkey_enc") {
		t.Errorf("bool dict key must route through __wisp_dkey_enc; got:\n%s", sh)
	}
	if strings.Contains(sh, "__wisp_fkey") {
		t.Errorf("bool dict key must not touch the float awk -v channel; got:\n%s", sh)
	}
}

func TestBoolEnumDictKeyOffAwkVChannel(t *testing.T) { // SC-025(c) / FR-012 bool backing
	src := `enum Flag: bool { On = true, Off = false }
fn main() -> int { let m: {Flag: int} = {}; m[Flag.On] = 1; return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_dkey_enc") {
		t.Errorf("bool-backed-enum dict key must route through __wisp_dkey_enc; got:\n%s", sh)
	}
	if strings.Contains(sh, "__wisp_fkey") {
		t.Errorf("bool-backed-enum dict key must not touch the float awk -v channel; got:\n%s", sh)
	}
}

// TestComparisonClassResolver asserts the ordering comparison-class resolver
// (Task 2) maps each ordered scalar operand to its class: raw float and a
// float-backed value enum -> cmpFloat (single float classifier via
// comparesAsFloat); the other value-enum backings dispatch on EnumInfo.Backing
// (string->cmpString, bool->cmpBool, int->cmpInt); plain scalars map directly.
func TestComparisonClassResolver(t *testing.T) {
	g := &gen{info: &types.Info{Enums: map[string]*types.EnumInfo{
		"Ratio@0": {Kind: types.EnumValue, Backing: types.Float},
		"Flag@0":  {Kind: types.EnumValue, Backing: types.Bool},
		"Color@0": {Kind: types.EnumValue, Backing: types.String},
		"Level@0": {Kind: types.EnumValue, Backing: types.Int},
	}}}
	cases := []struct {
		name string
		t    types.Type
		want cmpClass
	}{
		{"raw float", types.Float, cmpFloat},
		{"float-backed enum", types.Type("Ratio@0"), cmpFloat},
		{"bool-backed enum", types.Type("Flag@0"), cmpBool},
		{"string-backed enum", types.Type("Color@0"), cmpString},
		{"int-backed enum", types.Type("Level@0"), cmpInt},
		{"raw int", types.Int, cmpInt},
		{"raw bool", types.Bool, cmpBool},
		{"raw string", types.String, cmpString},
	}
	for _, c := range cases {
		if got := g.comparisonClass(c.t); got != c.want {
			t.Errorf("comparisonClass(%s): got %d, want %d", c.name, got, c.want)
		}
	}
}

// TestB2iTreeShakenWhenNoBoolOrdering asserts the __wisp_b2i helper (Task 2) is
// tree-shaken out of programs that never order bools (SC-009). Ordering only
// int/float here must not drag in the bool->0/1 map.
func TestB2iTreeShakenWhenNoBoolOrdering(t *testing.T) {
	src := `fn main() -> int {
	let a: int = 1
	let b: int = 2
	let x: float = 1.5
	let y: float = 2.5
	print("${a < b}")
	print("${x < y}")
	return 0
}`
	sh := string(compile(t, src))
	if strings.Contains(sh, "__wisp_b2i") {
		t.Errorf("SC-009: __wisp_b2i must be tree-shaken when no bool ordering is used; got:\n%s", sh)
	}
}

// TestBoolOrderingEmitsB2i asserts a bool `<` lowers through __wisp_b2i (FR-003
// positive): each operand's true/false text maps to 1/0 so false orders below
// true. Complements the SC-009 absence test.
func TestBoolOrderingEmitsB2i(t *testing.T) {
	src := `fn main() -> int { print("${false < true}"); return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_b2i") {
		t.Errorf("bool ordering must emit __wisp_b2i; got:\n%s", sh)
	}
}

// TestStringOrderingUsesScmp asserts a string `<` lowers through __wisp_scmp
// (byte-lexicographic), never a numeric `[ -lt ]` test.
func TestStringOrderingUsesScmp(t *testing.T) {
	src := `fn main() -> int { let a: string = "a"
let b: string = "b"
print("${a < b}"); return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_scmp") {
		t.Errorf("string ordering must emit __wisp_scmp; got:\n%s", sh)
	}
}

// TestFloatBackedEnumOrderingUsesFcmp asserts a float-backed value enum orders by
// numeric identity via __wisp_fcmp (the resolver's cmpFloat arm), the same path
// raw floats take.
func TestFloatBackedEnumOrderingUsesFcmp(t *testing.T) {
	src := `enum Ratio: float { Half = 0.5, Full = 1.0 }
fn main() -> int { print("${Ratio.Half < Ratio.Full}"); return 0 }`
	sh := string(compile(t, src))
	if !strings.Contains(sh, "__wisp_fcmp") {
		t.Errorf("float-backed-enum ordering must emit __wisp_fcmp; got:\n%s", sh)
	}
}

// TestOrderingOperandsAreDoubleQuoted asserts SC-012 for the new ordering paths:
// every __wisp_scmp / __wisp_b2i operand reaches the helper as a double-quoted
// "$..." expansion (never a bare word), so shell metacharacters in the value are
// data, not code. The helpers themselves read from awk ENVIRON / positional args,
// never interpolating the value into program text.
func TestOrderingOperandsAreDoubleQuoted(t *testing.T) {
	src := `fn main() -> int {
	let a: string = "a"
	let b: string = "b"
	let p: bool = false
	let q: bool = true
	print("${a < b}")
	print("${p < q}")
	return 0
}`
	sh := string(compile(t, src))
	for _, ln := range strings.Split(sh, "\n") {
		trimmed := strings.TrimSpace(ln)
		if !strings.HasPrefix(trimmed, "__wisp_scmp ") && !strings.HasPrefix(trimmed, "__wisp_b2i ") {
			continue
		}
		// Every operand token after the helper name must be a "$..."-quoted word.
		fields := strings.Fields(trimmed)
		for _, operand := range fields[1:] {
			if !strings.HasPrefix(operand, "\"$") {
				t.Errorf("SC-012: ordering helper operand %q is not a double-quoted expansion in line: %s", operand, trimmed)
			}
		}
	}
}
