package codegen

import (
	"strings"
	"testing"

	"github.com/mitchellnemitz/wisp/internal/parser"
	"github.com/mitchellnemitz/wisp/internal/types"
)

// compileWithMap parses, checks, and runs GenerateWithMap, failing on any error.
func compileWithMap(t *testing.T, src string) ([]byte, []*SourcePos) {
	t.Helper()
	prog, err := parser.Parse(src, "test.wisp")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	info := types.Check(prog)
	if len(info.Errors) > 0 {
		t.Fatalf("check errors: %v", info.Errors)
	}
	script, lm, err := GenerateWithMap(prog, info)
	if err != nil {
		t.Fatalf("GenerateWithMap: %v", err)
	}
	return script, lm
}

// TestLineMapLengthMatchesLines asserts one map entry per generated line (a
// generated line is a maximal run terminated by \n; a trailing \n does not
// create a phantom final empty entry).
func TestLineMapLengthMatchesLines(t *testing.T) {
	script, lm := compileWithMap(t, `fn main() -> int {
  print("hi")
  return 0
}`)
	want := countGeneratedLines(script)
	if len(lm) != want {
		t.Fatalf("len(lineMap) = %d, want %d (generated lines)", len(lm), want)
	}
}

// countGeneratedLines counts lines the same way the map convention does: one
// per \n-terminated run, no phantom trailing empty entry for a final \n.
func countGeneratedLines(script []byte) int {
	s := string(script)
	if s == "" {
		return 0
	}
	n := strings.Count(s, "\n")
	if !strings.HasSuffix(s, "\n") {
		n++ // last line without a trailing newline still counts
	}
	return n
}

// TestLineMapBannerPreludeNil asserts the shebang, banner, shellcheck directive,
// the blank line, and every prelude helper-body line are nil (no wisp origin).
func TestLineMapBannerPreludeNil(t *testing.T) {
	src := `fn main() -> int {
  print("${to_int("1")}")
  return 0
}`
	script, lm := compileWithMap(t, src)
	lines := strings.Split(strings.TrimSuffix(string(script), "\n"), "\n")
	if len(lines) != len(lm) {
		t.Fatalf("lines=%d lm=%d", len(lines), len(lm))
	}
	// Shebang, banner, shellcheck directive, zsh word-split shim, blank line.
	for i := 0; i < 5; i++ {
		if lm[i] != nil {
			t.Errorf("line %d (%q) maps to %v, want nil", i+1, lines[i], lm[i])
		}
	}
	// Every prelude helper-body line (those before the first `# test.wisp:` func
	// comment) must be nil.
	for i, ln := range lines {
		if strings.HasPrefix(ln, "# test.wisp:") {
			break
		}
		if lm[i] != nil {
			t.Errorf("prelude line %d (%q) maps to %v, want nil", i+1, ln, lm[i])
		}
	}
}

// TestLineMapUserStatementPos asserts the generated line emitting a known user
// statement maps to that statement's source position. The let on src line 2
// lowers to `<mangled>=7`; that line must map to line 2.
func TestLineMapUserStatementPos(t *testing.T) {
	src := `fn main() -> int {
  let a: int = 7
  return 0
}`
	script, lm := compileWithMap(t, src)
	lines := strings.Split(strings.TrimSuffix(string(script), "\n"), "\n")
	var found bool
	for i, ln := range lines {
		trimmed := strings.TrimSpace(ln)
		// The let assignment: `__wisp_v_<n>=7` (the mangler indexes locals).
		if strings.HasPrefix(trimmed, "__wisp_v_") && strings.HasSuffix(trimmed, "=7") {
			found = true
			if lm[i] == nil {
				t.Fatalf("let line %d (%q) maps to nil, want src 2", i+1, ln)
			}
			if lm[i].Line != 2 {
				t.Errorf("let line maps to line %d, want 2", lm[i].Line)
			}
			if lm[i].File != "test.wisp" {
				t.Errorf("let line file = %q, want test.wisp", lm[i].File)
			}
		}
	}
	if !found {
		t.Fatalf("did not find the let assignment line in:\n%s", script)
	}
}

// TestLineMapFooterNil asserts the footer line `__wisp_f_m0_main; exit "$__ret"`
// maps to nil.
func TestLineMapFooterNil(t *testing.T) {
	src := `fn main() -> int {
  return 0
}`
	script, lm := compileWithMap(t, src)
	lines := strings.Split(strings.TrimSuffix(string(script), "\n"), "\n")
	last := len(lines) - 1
	if !strings.Contains(lines[last], "; exit \"$__ret\"") {
		t.Fatalf("last line is not the footer: %q", lines[last])
	}
	if lm[last] != nil {
		t.Errorf("footer line maps to %v, want nil", lm[last])
	}
}

// TestLineMapExhaustive asserts EVERY generated line's entry for one small
// program (spec AC 2). The expected map is pinned to the exact emitted output:
//
//	1 #!/bin/sh                          nil  (banner)
//	2 # generated by wisp; do not edit   nil
//	3 # shellcheck disable=...           nil
//	4 if [ -n "${ZSH_VERSION:-}" ]; ...  nil  (zsh word-split shim)
//	5 (blank)                            nil
//	6..12 print() { ... }                nil  (prelude helper body)
//	13 (blank)                           nil  (trailing prelude blank)
//	14 # test.wisp:1                     line 1 (func comment)
//	15 __wisp_f_m0_main() {                 line 1 (func signature)
//	16 \tlocal __wisp_v_1                line 1 (genLocals)
//	17 \t__wisp_v_1=7                    line 2 (let a)
//	18 \t__wisp_t1="$__wisp_v_1"         line 3 (print interp temp)
//	19 \tprint "$__wisp_t1" 1            line 3 (print)
//	20 \t__ret=0                         line 4 (return)
//	21 \treturn                          line 4 (return)
//	22 }                                 line 1 (func close)
//	23 (blank)                           nil  (inter-function blank)
//	24 __wisp_f_m0_main; exit "$__ret"      nil  (footer)
func TestLineMapExhaustive(t *testing.T) {
	src := `fn main() -> int {
  let a: int = 7
  print("${a}")
  return 0
}`
	script, lm := compileWithMap(t, src)
	lines := strings.Split(strings.TrimSuffix(string(script), "\n"), "\n")
	if len(lines) != len(lm) {
		t.Fatalf("lines=%d lm=%d:\n%s", len(lines), len(lm), script)
	}
	if len(lines) != 24 {
		t.Fatalf("expected 24 generated lines, got %d:\n%s", len(lines), script)
	}
	// 0 = nil; n>0 = expected wisp source line.
	want := []int{
		0, 0, 0, 0, 0, // banner (shebang, comment, shellcheck, zsh shim, blank)
		0, 0, 0, 0, 0, 0, 0, // print() helper body (7 lines)
		0,       // trailing prelude blank
		1, 1, 1, // func comment, signature, locals
		2,    // let a
		3, 3, // print interp temp, print
		4, 4, // return: __ret=0, return
		1, // func close
		0, // inter-function blank
		0, // footer
	}
	if len(want) != len(lm) {
		t.Fatalf("test want table has %d entries, map has %d", len(want), len(lm))
	}
	for i, w := range want {
		switch {
		case w == 0:
			if lm[i] != nil {
				t.Errorf("line %d (%q): got %v, want nil", i+1, lines[i], lm[i])
			}
		case lm[i] == nil:
			t.Errorf("line %d (%q): got nil, want src line %d", i+1, lines[i], w)
		case lm[i].Line != w:
			t.Errorf("line %d (%q): got src line %d, want %d", i+1, lines[i], lm[i].Line, w)
		}
	}
}

// TestGenerateWrapsGenerateWithMap asserts Generate returns the same bytes as
// GenerateWithMap's script (Generate is a thin wrapper).
func TestGenerateWrapsGenerateWithMap(t *testing.T) {
	src := `fn main() -> int {
  print("hi")
  return 0
}`
	prog, err := parser.Parse(src, "test.wisp")
	if err != nil {
		t.Fatal(err)
	}
	info := types.Check(prog)
	a, err := Generate(prog, info)
	if err != nil {
		t.Fatal(err)
	}
	b, _, err := GenerateWithMap(prog, info)
	if err != nil {
		t.Fatal(err)
	}
	if string(a) != string(b) {
		t.Fatalf("Generate and GenerateWithMap disagree on script bytes")
	}
}
