#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_string() {
	__ret="$1"
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_bounds_fail() {
	__wisp_fail "$1" "array index out of bounds: index $2, length $3"
}

__wisp_repeat() {
	__rp_n="$3"
	if [ "$__rp_n" -lt 0 ]; then
		__wisp_fail "$1" "repeat(): negative count"
	fi
	__rp_out=""
	__rp_i=0
	while [ "$__rp_i" -lt "$__rp_n" ]; do
		__rp_out="$__rp_out$2"
		__rp_i=$(( __rp_i + 1 ))
	done
	__ret="$__rp_out"
}

__wisp_idiv_ovf() {
	[ "$3" -eq -1 ] || return
	__do_m=1
	while [ $(( __do_m + __do_m )) -gt 0 ]; do __do_m=$(( __do_m + __do_m )); done
	__do_min=$(( - (__do_m - 1) - __do_m - 1 ))
	if [ "$2" -eq "$__do_min" ]; then
		__wisp_fail "$1" "division overflow"
	fi
}

__wisp_chr() {
	if [ "$2" -lt 1 ] || [ "$2" -gt 255 ]; then
		__wisp_fail "$1" "chr(): code out of range 1-255"
	fi
	__chr_out="$(printf "\\$(printf '%03o' "$2")x")"
	__ret="${__chr_out%x}"
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_v_4 __wisp_v_5 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7 __wisp_t8 __wisp_t9 __wisp_t10 __wisp_t11 __wisp_t12
	__wisp_chr 'test.wisp:2:19' 65
	__wisp_t1="$__ret"
	__wisp_v_1="$__wisp_t1"
	__wisp_repeat 'test.wisp:3:19' 'x' 3
	__wisp_t2="$__ret"
	__wisp_v_2="$__wisp_t2"
	__wisp_alloc
	__wisp_t3="$__ret"
	__wisp_t4=1
	eval "__wisp_a_${__wisp_t3}_0=\$__wisp_t4"
	__wisp_t5=2
	eval "__wisp_a_${__wisp_t3}_1=\$__wisp_t5"
	__wisp_t6=3
	eval "__wisp_a_${__wisp_t3}_2=\$__wisp_t6"
	eval "__wisp_a_${__wisp_t3}_len=3"
	__wisp_v_3="$__wisp_t3"
	__wisp_t7=1
	eval "__ret=\$__wisp_a_${__wisp_v_3}_len"
	__wisp_t8="$__ret"
	case "$__wisp_t7" in -*) __wisp_bounds_fail 'test.wisp:5:17' "$__wisp_t7" "$__wisp_t8" ;; esac
	if [ "$__wisp_t7" -ge "$__wisp_t8" ]; then __wisp_bounds_fail 'test.wisp:5:17' "$__wisp_t7" "$__wisp_t8"; fi
	eval "__ret=\$__wisp_a_${__wisp_v_3}_${__wisp_t7}"
	__wisp_t9="$__ret"
	__wisp_v_4="$__wisp_t9"
	if [ 2 -eq 0 ]; then __wisp_fail 'test.wisp:6:18' "division by zero"; fi
	__wisp_idiv_ovf 'test.wisp:6:18' 7 2
	__wisp_t10=$(( 7 / 2 ))
	__wisp_v_5="$__wisp_t10"
	__wisp_print "$__wisp_v_1" 1
	__wisp_print "$__wisp_v_2" 1
	__wisp_string "$__wisp_v_4"
	__wisp_t11="$__ret"
	__wisp_print "$__wisp_t11" 1
	__wisp_string "$__wisp_v_5"
	__wisp_t12="$__ret"
	__wisp_print "$__wisp_t12" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
