#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_idiv_ovf() {
	[ "$3" -eq -1 ] || return
	__do_m=1
	while [ $(( __do_m + __do_m )) -gt 0 ]; do __do_m=$(( __do_m + __do_m )); done
	__do_min=$(( - (__do_m - 1) - __do_m - 1 ))
	if [ "$2" -eq "$__do_min" ]; then
		__wisp_fail "$1" "division overflow"
	fi
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7 __wisp_t8 __wisp_t9 __wisp_t10 __wisp_t11 __wisp_t12
	__wisp_t1=$(( 2 * 3 ))
	__wisp_t2=$(( 1 + __wisp_t1 ))
	__wisp_v_1="$__wisp_t2"
	if [ "$__wisp_v_1" = 7 ]; then __wisp_t4=true; else __wisp_t4=false; fi
	if [ "$__wisp_t4" = true ]; then
		if [ "$__wisp_v_1" -gt 0 ]; then __wisp_t5=true; else __wisp_t5=false; fi
		__wisp_t3="$__wisp_t5"
	else
		__wisp_t3=false
	fi
	__wisp_v_2="$__wisp_t3"
	__wisp_t6=$(( __wisp_v_1 - 1 ))
	if [ 2 -eq 0 ]; then __wisp_fail 'test.wisp:4:24' "division by zero"; fi
	__wisp_idiv_ovf 'test.wisp:4:24' "$__wisp_t6" 2
	__wisp_t7=$(( __wisp_t6 / 2 ))
	if [ 3 -eq 0 ]; then __wisp_fail 'test.wisp:4:32' "division by zero"; fi
	__wisp_t8=$(( __wisp_v_1 % 3 ))
	__wisp_t9=$(( __wisp_t7 + __wisp_t8 ))
	__wisp_v_3="$__wisp_t9"
	__wisp_t10="$__wisp_v_1"
	__wisp_print "$__wisp_t10" 1
	__wisp_t11="$__wisp_v_2"
	__wisp_print "$__wisp_t11" 1
	__wisp_t12="$__wisp_v_3"
	__wisp_print "$__wisp_t12" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
