#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_trim() {
	__t_s="$1"
	__t_cr="$(printf '\r')"
	while [ -n "$__t_s" ]; do
		__t_c="${__t_s%"${__t_s#?}"}"
		case "$__t_c" in
			' ' | '	' | '
' | "$__t_cr") __t_s="${__t_s#?}" ;;
			*) break ;;
		esac
	done
	while [ -n "$__t_s" ]; do
		__t_c="${__t_s#"${__t_s%?}"}"
		case "$__t_c" in
			' ' | '	' | '
' | "$__t_cr") __t_s="${__t_s%?}" ;;
			*) break ;;
		esac
	done
	__ret="$__t_s"
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_bounds_fail() {
	__wisp_fail "$1" "array index out of bounds: index $2, length $3"
}

# test.wisp:1
__wisp_f_m0_dbl() {
	local __wisp_v_1 __wisp_t1
	__wisp_v_1="$1"
	__wisp_t1=$(( $__wisp_v_1 * 2 ))
	__ret="$__wisp_t1"
	return
}

# test.wisp:2
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7 __wisp_t8 __wisp_t9 __wisp_t10 __wisp_t11 __wisp_t12 __wisp_t13 __wisp_t14 __wisp_t15
	__wisp_trim '  x  '
	__wisp_t1="$__ret"
	__wisp_v_1="$__wisp_t1"
	__wisp_alloc
	__wisp_t2="$__ret"
	__wisp_t3=1
	eval "__wisp_a_${__wisp_t2}_0=\$__wisp_t3"
	__wisp_t4=2
	eval "__wisp_a_${__wisp_t2}_1=\$__wisp_t4"
	eval "__wisp_a_${__wisp_t2}_len=2"
	__wisp_t5=__wisp_f_m0_dbl
	__wisp_alloc
	__wisp_t6="$__ret"
	__wisp_t7=0
	eval "__ret=\$__wisp_a_${__wisp_t2}_len"
	__wisp_t8="$__ret"
	__wisp_t9=0
	while [ "$__wisp_t9" -lt "$__wisp_t8" ]; do
		eval "__ret=\$__wisp_a_${__wisp_t2}_${__wisp_t9}"
		__wisp_t10="$__ret"
		"$__wisp_t5" "$__wisp_t10"
		__wisp_t11="$__ret"
		eval "__wisp_a_${__wisp_t6}_${__wisp_t7}=\$__wisp_t11"
		__wisp_t7=$(( $__wisp_t7 + 1 ))
		__wisp_t9=$(( $__wisp_t9 + 1 ))
	done
	eval "__wisp_a_${__wisp_t6}_len=\$__wisp_t7"
	__wisp_v_2="$__wisp_t6"
	__wisp_print "$__wisp_v_1" 1
	__wisp_t12=0
	eval "__ret=\$__wisp_a_${__wisp_v_2}_len"
	__wisp_t13="$__ret"
	case "$__wisp_t12" in -*) __wisp_bounds_fail 'test.wisp:6:14' "$__wisp_t12" "$__wisp_t13" ;; esac
	if [ "$__wisp_t12" -ge "$__wisp_t13" ]; then __wisp_bounds_fail 'test.wisp:6:14' "$__wisp_t12" "$__wisp_t13"; fi
	eval "__ret=\$__wisp_a_${__wisp_v_2}_${__wisp_t12}"
	__wisp_t14="$__ret"
	__wisp_t15="$__wisp_t14"
	__wisp_print "$__wisp_t15" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
