#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_ffinite() {
	__f_body="$2"
	case "$2" in
		-* | +*) __f_body="${2#?}" ;;
	esac
	case "$__f_body" in
		'' | *[!0-9.]* | .* | *. | *.*.*)
			__wisp_fail "$1" "float: non-finite or out-of-domain result: \"$2\"" ;;
	esac
	__ret="$2"
}

__wisp_fadd() {
	__f_r="$(LC_ALL=C awk -v a="$2" -v b="$3" 'BEGIN{ printf "%.17g", (a+0)+(b+0) }')"
	__wisp_ffinite "$1" "$__f_r"
}

# test.wisp:1
__wisp_f_m0_identity() {
	local __wisp_v_1
	__wisp_v_1="$1"
	__ret="$__wisp_v_1"
	return
}

# test.wisp:5
__wisp_f_m0_add__float() {
	local __wisp_v_1 __wisp_v_2 __wisp_t1
	__wisp_v_1="$1"
	__wisp_v_2="$2"
	__wisp_fadd 'test.wisp:6:11' "$__wisp_v_1" "$__wisp_v_2"
	__wisp_t1="$__ret"
	__ret="$__wisp_t1"
	return
}

# test.wisp:9
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5
	__wisp_f_m0_identity 41
	__wisp_t1="$__ret"
	__wisp_t2=$(( __wisp_t1 + 1 ))
	__wisp_v_1="$__wisp_t2"
	__wisp_f_m0_add__float 1.5 2.5
	__wisp_t3="$__ret"
	__wisp_v_2="$__wisp_t3"
	__wisp_t4="$__wisp_v_1"
	__wisp_print "$__wisp_t4" 1
	__wisp_t5="$__wisp_v_2"
	__wisp_print "$__wisp_t5" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
