#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	if [ "${__wisp_try_depth:-0}" -gt 0 ]; then
		if [ -z "$__wisp_err_pending" ]; then
			__wisp_err_msg="$1: $2"
			__wisp_err_code=
			__wisp_err_pos=
			__wisp_err_pending=1
		fi
		return
	fi
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_string() {
	__ret="$1"
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_idiv_ovf() {
	[ "$3" -eq -1 ] || return
	__do_m=1
	while [ $(( __do_m + __do_m )) -gt 0 ]; do __do_m=$(( __do_m + __do_m )); done
	__do_min=$(( - (__do_m - 1) - __do_m - 1 ))
	if [ "$2" -eq "$__do_min" ]; then
		__wisp_fail "$1" "division overflow"
		[ -n "$__wisp_err_pending" ] && return
	fi
}

__wisp_try_depth=0
__wisp_err_pending=
__wisp_err_msg=
__wisp_err_code=
__wisp_err_pos=
# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_v_1=10
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_v_2=0
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_sp_1="$__wisp_err_pending"; __wisp_sm_1="$__wisp_err_msg"
		__wisp_sc_1="$__wisp_err_code"; __wisp_ss_1="$__wisp_err_pos"
		__wisp_err_pending=
		__wisp_try_depth=$(( __wisp_try_depth + 1 ))
		if [ -z "$__wisp_err_pending" ]; then
			if [ "$__wisp_v_2" -eq 0 ]; then __wisp_fail 'test.wisp:5:20' "division by zero"; fi
			__wisp_idiv_ovf 'test.wisp:5:20' "$__wisp_v_1" "$__wisp_v_2"
			[ -n "$__wisp_err_pending" ] || __wisp_t1=$(( $__wisp_v_1 / $__wisp_v_2 ))
			if [ -z "$__wisp_err_pending" ]; then
				__wisp_string "$__wisp_t1"
				__wisp_t2="$__ret"
				__wisp_print "$__wisp_t2" 1
			fi
		fi
		if [ -n "$__wisp_err_pending" ]; then
			__wisp_alloc
			__wisp_t3="$__ret"
			eval "__wisp_s_${__wisp_t3}_message=\$__wisp_err_msg"
			__wisp_t4="${__wisp_err_code:-0}"
			eval "__wisp_s_${__wisp_t3}_code=\$__wisp_t4"
			__wisp_v_3="$__wisp_t3"
			__wisp_err_pending=
			if [ -z "$__wisp_err_pending" ]; then
				eval "__ret=\$__wisp_s_${__wisp_v_3}_message"
				__wisp_t5="$__ret"
				__wisp_print "$__wisp_t5" 1
			fi
		fi
		__wisp_try_depth=$(( __wisp_try_depth - 1 ))
		if [ -n "$__wisp_err_pending" ]; then
			if [ "$__wisp_try_depth" -eq 0 ]; then
				if [ -n "$__wisp_err_pos" ]; then printf 'wisp: %s: %s\n' "$__wisp_err_pos" "$__wisp_err_msg" >&2; else printf 'wisp: %s\n' "$__wisp_err_msg" >&2; fi
				exit 1
			fi
		else
			__wisp_err_pending="$__wisp_sp_1"; __wisp_err_msg="$__wisp_sm_1"
			__wisp_err_code="$__wisp_sc_1"; __wisp_err_pos="$__wisp_ss_1"
		fi
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__ret=0
		return
	fi
}

__wisp_f_m0_main; exit "$__ret"
