#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_v_4 __wisp_v_5 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5
	__wisp_v_1=3.14
	__wisp_v_2=0.0005
	__wisp_v_3=100.0
	__wisp_v_4=7
	if [ "$__wisp_v_4" -gt 0 ]; then __wisp_t1=true; else __wisp_t1=false; fi
	__wisp_v_5="$__wisp_t1"
	__wisp_t2="$__wisp_v_1"
	__wisp_print "$__wisp_t2" 1
	__wisp_t3="$__wisp_v_2"
	__wisp_print "$__wisp_t3" 1
	__wisp_t4="$__wisp_v_3"
	__wisp_print "$__wisp_t4" 1
	__wisp_t5="$__wisp_v_5"
	__wisp_print "$__wisp_t5" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
