#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_fstr() {
	__ret="$(LC_ALL=C awk -v a="$2" 'BEGIN{ printf "%.17g", (a+0) }')"
}

__wisp_sqrt() {
	__sq_r="$(LC_ALL=C awk -v a="$2" 'BEGIN{
		x = a + 0
		if (x < 0) { print "nan"; exit }
		if (x == 0) { printf "%.17g", 0; exit }
		# +inf guard: a float literal with a huge integer part overflows to +inf
		# in awk. For x > 0, only inf satisfies x == x/2; without this the
		# normalization loop below (y = y / 100) would never terminate. Print a
		# non-numeric token so the case-glob aborts located instead of hanging.
		if (x == x / 2) { print "inf"; exit }
		y = x; k = 0
		while (y >= 100) { y = y / 100; k = k + 1 }
		while (y < 1)    { y = y * 100; k = k - 1 }
		g = 5
		j = k
		while (j > 0) { g = g * 10; j = j - 1 }
		while (j < 0) { g = g / 10; j = j + 1 }
		i = 0
		while (i < 80) { g = (g + x / g) / 2; i = i + 1 }
		printf "%.17g", g
	}')"
	__sq_b="$__sq_r"
	case "$__sq_r" in -* | +*) __sq_b="${__sq_r#?}" ;; esac
	case "$__sq_b" in
		'' | *[!0-9.]* | .* | *. | *.*.*)
			__wisp_fail "$1" "sqrt(): non-finite or undefined result"
			[ -n "$__wisp_err_pending" ] && return ;;
	esac
	__ret="$__sq_r"
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_t1 __wisp_t2
	__wisp_sqrt 'test.wisp:2:18' 2.0
	__wisp_t1="$__ret"
	__wisp_v_1="$__wisp_t1"
	__wisp_fstr 'test.wisp:3:9' "$__wisp_v_1"
	__wisp_t2="$__ret"
	__wisp_print "$__wisp_t2" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
