#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_string() {
	__ret="$1"
}

__wisp_write_file() {
	printf '%s' "$3" > "$2" || __wisp_fail "$1" "write_file: cannot write $2"
}

__wisp_file_exists() {
	if [ -e "$1" ]; then __ret=true; else __ret=false; fi
}

__wisp_is_dir() {
	if [ -d "$1" ]; then __ret=true; else __ret=false; fi
}

__wisp_cwd() {
	__ret="$(pwd)"
}

__wisp_make_dir() {
	mkdir -p -- "$2" || __wisp_fail "$1" "make_dir: cannot create $2"
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_v_4 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7
	__wisp_make_dir 'test.wisp:2:3' 'd'
	__wisp_write_file 'test.wisp:3:3' 'd/f' 'hello'
	__wisp_file_exists 'd/f'
	__wisp_t1="$__ret"
	__wisp_v_1="$__wisp_t1"
	__wisp_is_dir 'd'
	__wisp_t2="$__ret"
	__wisp_v_2="$__wisp_t2"
	__wisp_is_dir 'd/f'
	__wisp_t3="$__ret"
	__wisp_v_3="$__wisp_t3"
	__wisp_cwd
	__wisp_t4="$__ret"
	__wisp_v_4="$__wisp_t4"
	__wisp_string "$__wisp_v_1"
	__wisp_t5="$__ret"
	__wisp_print "$__wisp_t5" 1
	__wisp_string "$__wisp_v_2"
	__wisp_t6="$__ret"
	__wisp_print "$__wisp_t6" 1
	__wisp_string "$__wisp_v_3"
	__wisp_t7="$__ret"
	__wisp_print "$__wisp_t7" 1
	__wisp_print "$__wisp_v_4" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
