#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

# test.wisp:1
__wisp_f_m0_greet() {
	local __wisp_v_1 __wisp_t1
	__wisp_v_1="$1"
	__wisp_t1='hello '"$__wisp_v_1"
	__wisp_print "$__wisp_t1" 1
}

# test.wisp:4
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_t1 __wisp_t2 __wisp_c1
	__wisp_t1=$(( 1 + 2 ))
	__wisp_v_1="$__wisp_t1"
	__wisp_v_2='world'
	__wisp_f_m0_greet "$__wisp_v_2"
	if [ "$__wisp_v_1" -gt 0 ]; then __wisp_t2=true; else __wisp_t2=false; fi
	__wisp_c1="$__wisp_t2"
	if [ "$__wisp_c1" = true ]; then
		__wisp_print 'positive' 1
	fi
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
