#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_string() {
	__ret="$1"
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_v_4 __wisp_v_5 __wisp_v_6 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7 __wisp_t8 __wisp_t9 __wisp_t10 __wisp_t11 __wisp_t12 __wisp_t13 __wisp_t14 __wisp_t15 __wisp_t16 __wisp_t17 __wisp_t18 __wisp_t19 __wisp_t20 __wisp_t21
	__wisp_alloc
	__wisp_t1="$__ret"
	__wisp_t2=some
	eval "__wisp_s_${__wisp_t1}_tag=\$__wisp_t2"
	__wisp_t3=42
	eval "__wisp_s_${__wisp_t1}_value=\$__wisp_t3"
	__wisp_v_1="$__wisp_t1"
	__wisp_alloc
	__wisp_t4="$__ret"
	__wisp_t5=none
	eval "__wisp_s_${__wisp_t4}_tag=\$__wisp_t5"
	__wisp_v_2="$__wisp_t4"
	__wisp_alloc
	__wisp_t6="$__ret"
	__wisp_t7=ok
	eval "__wisp_s_${__wisp_t6}_tag=\$__wisp_t7"
	__wisp_t8=10
	eval "__wisp_s_${__wisp_t6}_value=\$__wisp_t8"
	__wisp_v_3="$__wisp_t6"
	eval "__ret=\$__wisp_s_${__wisp_v_1}_tag"
	__wisp_t9="$__ret"
	if [ "$__wisp_t9" = some ]; then
		eval "__ret=\$__wisp_s_${__wisp_v_1}_value"
		__wisp_t10="$__ret"
		__wisp_v_4="$__wisp_t10"
		__wisp_string "$__wisp_v_4"
		__wisp_t11="$__ret"
		__wisp_print "$__wisp_t11" 1
	elif [ "$__wisp_t9" = none ]; then
		__wisp_print 'none' 1
	fi
	eval "__ret=\$__wisp_s_${__wisp_v_3}_tag"
	__wisp_t12="$__ret"
	if [ "$__wisp_t12" = ok ]; then
		eval "__ret=\$__wisp_s_${__wisp_v_3}_value"
		__wisp_t13="$__ret"
		__wisp_v_5="$__wisp_t13"
		__wisp_string "$__wisp_v_5"
		__wisp_t14="$__ret"
		__wisp_print "$__wisp_t14" 1
	elif [ "$__wisp_t12" = err ]; then
		eval "__ret=\$__wisp_s_${__wisp_v_3}_value"
		__wisp_t15="$__ret"
		__wisp_v_6="$__wisp_t15"
		eval "__ret=\$__wisp_s_${__wisp_v_6}_message"
		__wisp_t16="$__ret"
		eval "__ret=\$__wisp_s_${__wisp_v_6}_code"
		__wisp_t17="$__ret"
		__wisp_t18='error("'"$__wisp_t16"'", '"$__wisp_t17"')'
		__wisp_print "$__wisp_t18" 1
	fi
	eval "__ret=\$__wisp_s_${__wisp_v_2}_tag"
	__wisp_t19="$__ret"
	case "$__wisp_t19" in
		some)
			eval "__ret=\$__wisp_s_${__wisp_v_2}_value"
			__wisp_t21="$__ret"
			__wisp_t20="Some($__wisp_t21)"
		;;
		*)
			__wisp_t20="None"
		;;
	esac
	__wisp_print "$__wisp_t20" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
