#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_pow() {
	__pw_r="$(LC_ALL=C awk -v pos="$1" -v b="$2" -v e="$3" 'BEGIN{
		b = b + 0; e = e + 0
		if (b == 1 || e == 0) { printf "%.17g", 1; exit }
		if (b == 0) {
			if (e > 0) { printf "%.17g", 0; exit }
			print "nan"; exit
		}
		# check if exponent is integer-valued
		ei = int(e); is_int = (e == ei)
		if (b < 0 && !is_int) { print "nan"; exit }
		# integer exponent via repeated squaring
		if (is_int) {
			neg = 0; en = ei
			if (en < 0) { neg = 1; en = -en }
			acc = 1; base = b
			while (en > 0) {
				if (en % 2 == 1) acc = acc * base
				base = base * base; en = int(en / 2)
			}
			if (neg) acc = 1 / acc
			printf "%.17g", acc; exit
		}
		# float exponent: exp(e * ln(b))
		# ln via atanh series: ln(x) = 2*atanh((x-1)/(x+1))
		# atanh(t) = t + t^3/3 + t^5/5 + ... (|t|<1); use range reduction to keep |t|<0.3
		x = b; k = 0
		while (x >= 1.2) { x = x / 2; k = k + 1 }
		while (x < 0.6)  { x = x * 2; k = k - 1 }
		t = (x - 1) / (x + 1)
		t2 = t * t; s = t; p = t; n = 1
		while (n < 200) {
			n = n + 2; p = p * t2; s = s + p / n
			if (p / n < 1e-17 && p / n > -1e-17) break
		}
		ln_b = 2 * s + k * 0.6931471805599453
		lp = e * ln_b
		# exp via Taylor: e^x = 1 + x + x^2/2! + ...
		acc = 1; term = 1; n = 0
		while (n < 300) {
			n = n + 1; term = term * lp / n; acc = acc + term
			if (term < 1e-17 && term > -1e-17) break
		}
		printf "%.17g", acc
	}')"
	__pw_b="$__pw_r"
	case "$__pw_r" in -* | +*) __pw_b="${__pw_r#?}" ;; esac
	case "$__pw_b" in
		'' | *[!0-9.]* | .* | *. | *.*.*)
			__wisp_fail "$1" "pow(): non-finite or undefined result"
			[ -n "$__wisp_err_pending" ] && return ;;
	esac
	__ret="$__pw_r"
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4
	__wisp_pow 'test.wisp:2:18' 2.0 0.5
	__wisp_t1="$__ret"
	__wisp_v_1="$__wisp_t1"
	__wisp_pow 'test.wisp:3:18' 2.0 10.0
	__wisp_t2="$__ret"
	__wisp_v_2="$__wisp_t2"
	__wisp_t3="$__wisp_v_1"
	__wisp_print "$__wisp_t3" 1
	__wisp_t4="$__wisp_v_2"
	__wisp_print "$__wisp_t4" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
