#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_read_line() {
	__wisp_rl_line=""
	IFS= read -r __wisp_rl_line
	__wisp_rl_rc=$?
	if [ "$__wisp_rl_rc" -ne 0 ] && [ -z "$__wisp_rl_line" ]; then
		__wisp_rl_eof=1
		__ret=""
	else
		__wisp_rl_eof=
		__ret="$__wisp_rl_line"
	fi
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7
	__wisp_read_line
	__wisp_t1="$__ret"
	__wisp_t2="$__wisp_rl_eof"
	__wisp_alloc
	__wisp_t3="$__ret"
	if [ -n "$__wisp_t2" ]; then
		__wisp_t4=none
		eval "__wisp_s_${__wisp_t3}_tag=\$__wisp_t4"
	else
		__wisp_t5=some
		eval "__wisp_s_${__wisp_t3}_tag=\$__wisp_t5"
		eval "__wisp_s_${__wisp_t3}_value=\$__wisp_t1"
	fi
	eval "__ret=\$__wisp_s_${__wisp_t3}_tag"
	__wisp_t6="$__ret"
	if [ "$__wisp_t6" = some ]; then
		eval "__ret=\$__wisp_s_${__wisp_t3}_value"
		__wisp_t7="$__ret"
		__wisp_v_1="$__wisp_t7"
		__wisp_print "$__wisp_v_1" 1
	elif [ "$__wisp_t6" = none ]; then
		__wisp_print 'none' 1
	fi
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
