#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_run() {
	__wisp_run_pos="$1"
	__wisp_run_id="$2"
	eval "__ret=\$__wisp_a_${__wisp_run_id}_len"
	__wisp_run_len="$__ret"
	if [ "$__wisp_run_len" -eq 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: empty argv"
	fi
	set --
	__wisp_run_i=0
	while [ "$__wisp_run_i" -lt "$__wisp_run_len" ]; do
		eval "set -- \"\$@\" \"\$__wisp_a_${__wisp_run_id}_${__wisp_run_i}\""
		__wisp_run_i=$(( __wisp_run_i + 1 ))
	done
	__ret="$( "$@" )"
	__wisp_run_rc=$?
	if [ "$__wisp_run_rc" -ne 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: $1 exited with status $__wisp_run_rc"
	fi
}

__wisp_run_full() {
	__wisp_rf_id="$2"
	eval "__wisp_rf_n=\$__wisp_a_${__wisp_rf_id}_len"
	if [ -z "$__wisp_rf_n" ] || [ "$__wisp_rf_n" -eq 0 ]; then
		__wisp_fail "$1" "run_full: empty argv"
	fi
	__wisp_rf_t1="$(mktemp)" || { __wisp_fail "$1" "run_full: mktemp failed"; [ -n "$__wisp_err_pending" ] && return; }
	__wisp_rf_t2="$(mktemp)" || { rm -f "$__wisp_rf_t1"; __wisp_fail "$1" "run_full: mktemp failed"; [ -n "$__wisp_err_pending" ] && return; }
	set --
	__wisp_rf_i=0
	while [ "$__wisp_rf_i" -lt "$__wisp_rf_n" ]; do
		eval "set -- \"\$@\" \"\$__wisp_a_${__wisp_rf_id}_${__wisp_rf_i}\""
		__wisp_rf_i=$(( __wisp_rf_i + 1 ))
	done
	"$@" < /dev/null > "$__wisp_rf_t1" 2> "$__wisp_rf_t2"
	__wisp_rf_code=$?
	__wisp_rf_sout="$(cat "$__wisp_rf_t1"; printf x)"
	__wisp_rf_serr="$(cat "$__wisp_rf_t2"; printf x)"
	__wisp_rf_stdout="${__wisp_rf_sout%x}"
	__wisp_rf_stderr="${__wisp_rf_serr%x}"
	rm -f "$__wisp_rf_t1" "$__wisp_rf_t2"
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7 __wisp_t8
	__wisp_alloc
	__wisp_t1="$__ret"
	__wisp_t2='echo'
	eval "__wisp_a_${__wisp_t1}_0=\$__wisp_t2"
	__wisp_t3='hi'
	eval "__wisp_a_${__wisp_t1}_1=\$__wisp_t3"
	eval "__wisp_a_${__wisp_t1}_len=2"
	__wisp_run 'test.wisp:2:19' "$__wisp_t1"
	__wisp_t4="$__ret"
	__wisp_v_1="$__wisp_t4"
	__wisp_alloc
	__wisp_t5="$__ret"
	__wisp_t6='echo'
	eval "__wisp_a_${__wisp_t5}_0=\$__wisp_t6"
	__wisp_t7='world'
	eval "__wisp_a_${__wisp_t5}_1=\$__wisp_t7"
	eval "__wisp_a_${__wisp_t5}_len=2"
	__wisp_run_full 'test.wisp:3:22' "$__wisp_t5"
	__wisp_alloc
	__wisp_t8="$__ret"
	eval "__wisp_s_${__wisp_t8}_stdout=\$__wisp_rf_stdout"
	eval "__wisp_s_${__wisp_t8}_stderr=\$__wisp_rf_stderr"
	eval "__wisp_s_${__wisp_t8}_code=\$__wisp_rf_code"
	__wisp_v_2="$__wisp_t8"
	__wisp_print "$__wisp_v_1" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
