#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_string() {
	__ret="$1"
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_hexdig() {
	case "$1" in
		0) __ret=0 ;; 1) __ret=1 ;; 2) __ret=2 ;; 3) __ret=3 ;;
		4) __ret=4 ;; 5) __ret=5 ;; 6) __ret=6 ;; 7) __ret=7 ;;
		8) __ret=8 ;; 9) __ret=9 ;; 10) __ret=a ;; 11) __ret=b ;;
		12) __ret=c ;; 13) __ret=d ;; 14) __ret=e ;; 15) __ret=f ;;
	esac
}

__wisp_dkey_enc() {
	local LC_ALL
	LC_ALL=C
	__de_s="$1"
	__de_o="k"
	while [ -n "$__de_s" ]; do
		__de_c="${__de_s%"${__de_s#?}"}"
		__de_s="${__de_s#?}"
		__de_n=$(printf '%d' "'$__de_c")
		__de_n=$(( __de_n & 255 ))
		__wisp_hexdig $(( __de_n / 16 ))
		__de_hi="$__ret"
		__wisp_hexdig $(( __de_n % 16 ))
		__de_o="$__de_o$__de_hi$__ret"
	done
	__ret="$__de_o"
}

__wisp_run() {
	__wisp_run_pos="$1"
	__wisp_run_id="$2"
	eval "__ret=\$__wisp_a_${__wisp_run_id}_len"
	__wisp_run_len="$__ret"
	if [ "$__wisp_run_len" -eq 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: empty argv"
	fi
	set --
	__wisp_run_i=0
	while [ "$__wisp_run_i" -lt "$__wisp_run_len" ]; do
		eval "set -- \"\$@\" \"\$__wisp_a_${__wisp_run_id}_${__wisp_run_i}\""
		__wisp_run_i=$(( __wisp_run_i + 1 ))
	done
	__ret="$( "$@" )"
	__wisp_run_rc=$?
	if [ "$__wisp_run_rc" -ne 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: $1 exited with status $__wisp_run_rc"
	fi
}

__wisp_run_status() {
	__wisp_rs_pos="$1"
	__wisp_rs_id="$2"
	eval "__ret=\$__wisp_a_${__wisp_rs_id}_len"
	__wisp_rs_len="$__ret"
	if [ "$__wisp_rs_len" -eq 0 ]; then
		__wisp_fail "$__wisp_rs_pos" "run_status: empty argv"
	fi
	set --
	__wisp_rs_i=0
	while [ "$__wisp_rs_i" -lt "$__wisp_rs_len" ]; do
		eval "set -- \"\$@\" \"\$__wisp_a_${__wisp_rs_id}_${__wisp_rs_i}\""
		__wisp_rs_i=$(( __wisp_rs_i + 1 ))
	done
	"$@"
	__ret=$?
}

__wisp_run_full() {
	__wisp_rf_id="$2"
	eval "__wisp_rf_n=\$__wisp_a_${__wisp_rf_id}_len"
	if [ -z "$__wisp_rf_n" ] || [ "$__wisp_rf_n" -eq 0 ]; then
		__wisp_fail "$1" "run_full: empty argv"
	fi
	__wisp_rf_t1="$(mktemp)" || { __wisp_fail "$1" "run_full: mktemp failed"; [ -n "$__wisp_err_pending" ] && return; }
	__wisp_rf_t2="$(mktemp)" || { rm -f "$__wisp_rf_t1"; __wisp_fail "$1" "run_full: mktemp failed"; [ -n "$__wisp_err_pending" ] && return; }
	set --
	__wisp_rf_i=0
	while [ "$__wisp_rf_i" -lt "$__wisp_rf_n" ]; do
		eval "set -- \"\$@\" \"\$__wisp_a_${__wisp_rf_id}_${__wisp_rf_i}\""
		__wisp_rf_i=$(( __wisp_rf_i + 1 ))
	done
	"$@" < /dev/null > "$__wisp_rf_t1" 2> "$__wisp_rf_t2"
	__wisp_rf_code=$?
	__wisp_rf_sout="$(cat "$__wisp_rf_t1"; printf x)"
	__wisp_rf_serr="$(cat "$__wisp_rf_t2"; printf x)"
	__wisp_rf_stdout="${__wisp_rf_sout%x}"
	__wisp_rf_stderr="${__wisp_rf_serr%x}"
	rm -f "$__wisp_rf_t1" "$__wisp_rf_t2"
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_v_4 __wisp_v_5 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4 __wisp_t5 __wisp_t6 __wisp_t7 __wisp_t8 __wisp_t9 __wisp_t10 __wisp_t11 __wisp_t12 __wisp_t13 __wisp_t14 __wisp_t15 __wisp_t16 __wisp_t17 __wisp_t18 __wisp_t19 __wisp_t20 __wisp_t21
	__wisp_alloc
	__wisp_t1="$__ret"
	__wisp_t2='echo'
	eval "__wisp_a_${__wisp_t1}_0=\$__wisp_t2"
	__wisp_t3='hi'
	eval "__wisp_a_${__wisp_t1}_1=\$__wisp_t3"
	eval "__wisp_a_${__wisp_t1}_len=2"
	__wisp_run 'test.wisp:2:21' "$__wisp_t1"
	__wisp_t4="$__ret"
	__wisp_v_1="$__wisp_t4"
	__wisp_alloc
	__wisp_t5="$__ret"
	__wisp_t6='true'
	eval "__wisp_a_${__wisp_t5}_0=\$__wisp_t6"
	eval "__wisp_a_${__wisp_t5}_len=1"
	__wisp_run_status 'test.wisp:3:17' "$__wisp_t5"
	__wisp_t7="$__ret"
	__wisp_v_2="$__wisp_t7"
	__wisp_alloc
	__wisp_t8="$__ret"
	__wisp_t9='echo'
	eval "__wisp_a_${__wisp_t8}_0=\$__wisp_t9"
	__wisp_t10='world'
	eval "__wisp_a_${__wisp_t8}_1=\$__wisp_t10"
	eval "__wisp_a_${__wisp_t8}_len=2"
	__wisp_run_full 'test.wisp:4:22' "$__wisp_t8"
	__wisp_alloc
	__wisp_t11="$__ret"
	eval "__wisp_s_${__wisp_t11}_stdout=\$__wisp_rf_stdout"
	eval "__wisp_s_${__wisp_t11}_stderr=\$__wisp_rf_stderr"
	eval "__wisp_s_${__wisp_t11}_code=\$__wisp_rf_code"
	__wisp_v_3="$__wisp_t11"
	__wisp_alloc
	__wisp_t12="$__ret"
	eval "__wisp_d_${__wisp_t12}_keys=''"
	__wisp_dkey_enc 'K'
	__wisp_t13="$__ret"
	__wisp_t14='v'
	eval "__wisp_d_${__wisp_t12}_${__wisp_t13}=\$__wisp_t14"
	eval "__ret=\$__wisp_d_${__wisp_t12}_keys"
	__wisp_t15="$__ret"
	case " $__wisp_t15 " in
		*" $__wisp_t13 "*) : ;;
		*) eval "__wisp_d_${__wisp_t12}_keys=\"\$__wisp_t15 \$__wisp_t13\"" ;;
	esac
	__wisp_v_4="$__wisp_t12"
	__wisp_t16='x'
	__wisp_dkey_enc 'K'
	__wisp_t17="$__ret"
	eval "__ret=\$__wisp_d_${__wisp_v_4}_keys"
	__wisp_t18="$__ret"
	case " $__wisp_t18 " in
		*" $__wisp_t17 "*) eval "__wisp_t19=\$__wisp_d_${__wisp_v_4}_${__wisp_t17}" ;;
		*) __wisp_t19="$__wisp_t16" ;;
	esac
	__wisp_v_5="$__wisp_t19"
	__wisp_print "$__wisp_v_1" 1
	__wisp_string "$__wisp_v_2"
	__wisp_t20="$__ret"
	__wisp_print "$__wisp_t20" 1
	eval "__ret=\$__wisp_s_${__wisp_v_3}_stdout"
	__wisp_t21="$__ret"
	__wisp_print "$__wisp_t21" 1
	__wisp_print "$__wisp_v_5" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
