#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_run() {
	__wisp_run_pos="$1"
	__wisp_run_id="$2"
	eval "__ret=\$__wisp_a_${__wisp_run_id}_len"
	__wisp_run_len="$__ret"
	if [ "$__wisp_run_len" -eq 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: empty argv"
	fi
	set --
	__wisp_run_i=0
	while [ "$__wisp_run_i" -lt "$__wisp_run_len" ]; do
		eval "set -- \"\$@\" \"\$__wisp_a_${__wisp_run_id}_${__wisp_run_i}\""
		__wisp_run_i=$(( __wisp_run_i + 1 ))
	done
	__ret="$( "$@" )"
	__wisp_run_rc=$?
	if [ "$__wisp_run_rc" -ne 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: $1 exited with status $__wisp_run_rc"
	fi
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_t1 __wisp_t2 __wisp_t3 __wisp_t4
	__wisp_alloc
	__wisp_t1="$__ret"
	__wisp_t2='echo'
	eval "__wisp_a_${__wisp_t1}_0=\$__wisp_t2"
	__wisp_t3='hi'
	eval "__wisp_a_${__wisp_t1}_1=\$__wisp_t3"
	eval "__wisp_a_${__wisp_t1}_len=2"
	__wisp_run 'test.wisp:2:21' "$__wisp_t1"
	__wisp_t4="$__ret"
	__wisp_v_1="$__wisp_t4"
	__wisp_print "$__wisp_v_1" 1
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
