#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_fail() {
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

__wisp_symlink() {
	ln -s -- "$2" "$3" || { __wisp_fail "$1" "symlink: failed"; }
}

# test.wisp:1
__wisp_f_m0_main() {
	__wisp_symlink 'test.wisp:2:3' 't' 'l'
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
