#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043
if [ -n "${ZSH_VERSION:-}" ]; then emulate sh 2>/dev/null || setopt shwordsplit; FUNCNEST=1000000; fi

__wisp_print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_int_max() {
	__im_m=1
	while [ $(( __im_m + __im_m )) -gt 0 ]; do __im_m=$(( __im_m + __im_m )); done
	__im_r=$(( __im_m - 1 ))
	__ret=$(( __im_r + __im_m ))
}

# test.wisp:1
__wisp_f_m0_main() {
	local __wisp_v_1 __wisp_t1 __wisp_t2 __wisp_c1
	__wisp_int_max
	__wisp_t1="$__ret"
	__wisp_v_1="$__wisp_t1"
	if [ "$__wisp_v_1" -gt 0 ]; then __wisp_t2=true; else __wisp_t2=false; fi
	__wisp_c1="$__wisp_t2"
	if [ "$__wisp_c1" = true ]; then
		__wisp_print 'big' 1
	else
		__wisp_print 'small' 1
	fi
	__ret=0
	return
}

__wisp_f_m0_main; exit "$__ret"
