#!/bin/sh
# generated by wisp; do not edit
# shellcheck disable=SC3043,SC2050,SC2043

__wisp_fail() {
	if [ "${__wisp_try_depth:-0}" -gt 0 ]; then
		if [ -z "$__wisp_err_pending" ]; then
			__wisp_err_msg="$1: $2"
			__wisp_err_pending=1
		fi
		return
	fi
	printf 'wisp: %s: %s\n' "$1" "$2" >&2
	exit 1
}

print() {
	if [ "$2" = 2 ]; then
		printf '%s\n' "$1" >&2
	else
		printf '%s\n' "$1"
	fi
}

__wisp_string() {
	__ret="$1"
}

__wisp_alloc() {
	__wisp_next_id=$(( ${__wisp_next_id:-0} + 1 ))
	__ret="$__wisp_next_id"
}

__wisp_env() {
	if awk -v n="$2" 'BEGIN{ exit !(n in ENVIRON) }'; then
		__ret="$(awk -v n="$2" 'BEGIN{ printf "%s", ENVIRON[n] }')"
	else
		__wisp_fail "$1" "env: $2 is not set"
		[ -n "$__wisp_err_pending" ] && return
	fi
}

__wisp_has_env() {
	if awk -v n="$1" 'BEGIN{ exit !(n in ENVIRON) }'; then
		__ret=true
	else
		__ret=false
	fi
}

__wisp_read_file() {
	__rf_out="$(cat -- "$2" && printf x)" || __wisp_fail "$1" "read_file: cannot read $2"
	[ -n "$__wisp_err_pending" ] && return
	tr -d '\000' < "$2" | cmp -s - "$2" || __wisp_fail "$1" "read_file: $2 contains a NUL byte (unsupported)"
	[ -n "$__wisp_err_pending" ] && return
	__ret="${__rf_out%x}"
}

__wisp_write_file() {
	printf '%s' "$3" > "$2" || __wisp_fail "$1" "write_file: cannot write $2"
	[ -n "$__wisp_err_pending" ] && return
}

__wisp_append_file() {
	printf '%s' "$3" >> "$2" || __wisp_fail "$1" "append_file: cannot write $2"
	[ -n "$__wisp_err_pending" ] && return
}

__wisp_run() {
	__wisp_run_pos="$1"
	__wisp_run_id="$2"
	eval "__ret=\$__wisp_a_${__wisp_run_id}_len"
	__wisp_run_len="$__ret"
	if [ "$__wisp_run_len" -eq 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: empty argv"
		[ -n "$__wisp_err_pending" ] && return
	fi
	set --
	__wisp_run_i=0
	while [ "$__wisp_run_i" -lt "$__wisp_run_len" ]; do
		eval "set -- \"\$@\" \"\$__wisp_a_${__wisp_run_id}_${__wisp_run_i}\""
		__wisp_run_i=$(( __wisp_run_i + 1 ))
	done
	__ret="$( "$@" )"
	__wisp_run_rc=$?
	[ -n "$__wisp_err_pending" ] && return
	if [ "$__wisp_run_rc" -ne 0 ]; then
		__wisp_fail "$__wisp_run_pos" "run: $1 exited with status $__wisp_run_rc"
		[ -n "$__wisp_err_pending" ] && return
	fi
}

__wisp_try_depth=0
__wisp_err_pending=
__wisp_err_msg=
# testdata/golden/io_injection.wisp:1
__wisp_f_main() {
	local __wisp_v_1 __wisp_v_2 __wisp_v_3 __wisp_v_4
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_v_1='$(echo PWN); `id`; rm -rf x'
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_write_file 'testdata/golden/io_injection.wisp:3:3' 'inj_file' "$__wisp_v_1"
		if [ -z "$__wisp_err_pending" ]; then
			:
		fi
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_append_file 'testdata/golden/io_injection.wisp:4:3' 'inj_file' "$__wisp_v_1"
		if [ -z "$__wisp_err_pending" ]; then
			:
		fi
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_read_file 'testdata/golden/io_injection.wisp:5:22' 'inj_file'
		__wisp_t1="$__ret"
		if [ -z "$__wisp_err_pending" ]; then
			__wisp_v_2="$__wisp_t1"
		fi
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_t2='rf='"$__wisp_v_2"
		print "$__wisp_t2" 1
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_has_env "$__wisp_v_1"
		__wisp_t3="$__ret"
		__wisp_string "$__wisp_t3"
		__wisp_t4="$__ret"
		__wisp_t5='hasenv='"$__wisp_t4"
		print "$__wisp_t5" 1
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_alloc
		__wisp_t6="$__ret"
		__wisp_t7='echo'
		eval "__wisp_a_${__wisp_t6}_0=\$__wisp_t7"
		eval "__wisp_a_${__wisp_t6}_1=\$__wisp_v_1"
		eval "__wisp_a_${__wisp_t6}_len=2"
		__wisp_run 'testdata/golden/io_injection.wisp:8:21' "$__wisp_t6"
		__wisp_t8="$__ret"
		if [ -z "$__wisp_err_pending" ]; then
			__wisp_v_3="$__wisp_t8"
		fi
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_t9='run='"$__wisp_v_3"
		print "$__wisp_t9" 1
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__wisp_sp_1="$__wisp_err_pending"; __wisp_sm_1="$__wisp_err_msg"
		__wisp_err_pending=
		__wisp_try_depth=$(( __wisp_try_depth + 1 ))
		if [ -z "$__wisp_err_pending" ]; then
			__wisp_env 'testdata/golden/io_injection.wisp:11:11' "$__wisp_v_1"
			__wisp_t10="$__ret"
			if [ -z "$__wisp_err_pending" ]; then
				print "$__wisp_t10" 1
			fi
		fi
		if [ -n "$__wisp_err_pending" ]; then
			__wisp_alloc
			__wisp_t11="$__ret"
			eval "__wisp_s_${__wisp_t11}_message=\$__wisp_err_msg"
			__wisp_v_4="$__wisp_t11"
			__wisp_err_pending=
			if [ -z "$__wisp_err_pending" ]; then
				print 'env-unset' 1
			fi
		fi
		__wisp_try_depth=$(( __wisp_try_depth - 1 ))
		if [ -n "$__wisp_err_pending" ]; then
			if [ "$__wisp_try_depth" -eq 0 ]; then printf 'wisp: %s\n' "$__wisp_err_msg" >&2; exit 1; fi
		else
			__wisp_err_pending="$__wisp_sp_1"; __wisp_err_msg="$__wisp_sm_1"
		fi
	fi
	if [ -z "$__wisp_err_pending" ]; then
		__ret=0
		return
	fi
}

__wisp_f_main; exit "$__ret"
